// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnq0o3cP0AOl4OYhX-S-IL_JIZ9Y2GBpE',
    appId: '1:940230830659:web:2085283dfc9dedaae6c2f6',
    messagingSenderId: '940230830659',
    projectId: 'healing-animal-sounds',
    authDomain: 'healing-animal-sounds.firebaseapp.com',
    storageBucket: 'healing-animal-sounds.appspot.com',
    measurementId: 'G-QM17CLX2QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7BSMAYswYTLjAe_IFuwWpW48uxZ1ZC0',
    appId: '1:940230830659:android:417e7d16a55fd788e6c2f6',
    messagingSenderId: '940230830659',
    projectId: 'healing-animal-sounds',
    storageBucket: 'healing-animal-sounds.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5gB-hJraCCP3_NeqUt1YvJgcPKkXeM5g',
    appId: '1:940230830659:ios:5d472fd33d82c004e6c2f6',
    messagingSenderId: '940230830659',
    projectId: 'healing-animal-sounds',
    storageBucket: 'healing-animal-sounds.appspot.com',
    androidClientId: '940230830659-lp90e9g0fkbi8eevmtstgaso7d4nbde3.apps.googleusercontent.com',
    iosClientId: '940230830659-ec9jm1q55tiv73oa1skh1e4418jot0vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gB-hJraCCP3_NeqUt1YvJgcPKkXeM5g',
    appId: '1:940230830659:ios:5d472fd33d82c004e6c2f6',
    messagingSenderId: '940230830659',
    projectId: 'healing-animal-sounds',
    storageBucket: 'healing-animal-sounds.appspot.com',
    androidClientId: '940230830659-lp90e9g0fkbi8eevmtstgaso7d4nbde3.apps.googleusercontent.com',
    iosClientId: '940230830659-ec9jm1q55tiv73oa1skh1e4418jot0vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnq0o3cP0AOl4OYhX-S-IL_JIZ9Y2GBpE',
    appId: '1:940230830659:web:f11deeb4d1223a25e6c2f6',
    messagingSenderId: '940230830659',
    projectId: 'healing-animal-sounds',
    authDomain: 'healing-animal-sounds.firebaseapp.com',
    storageBucket: 'healing-animal-sounds.appspot.com',
    measurementId: 'G-TV372KF89P',
  );

}